CREATE TABLE IF NOT EXISTS `Packages` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
	`branch` VARCHAR(255) NOT NULL,
	`cluster` VARCHAR(100) NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `status` VARCHAR(100) NOT NULL,
    `path` TEXT NOT NULL,
    `version` VARCHAR(255) NOT NULL
)
;