CREATE TABLE IF NOT EXISTS `Ingredients` (
        `ingredient_id` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
        `ingredient_name` VARCHAR(255) NOT NULL UNIQUE,
        `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
;