CREATE TABLE IF NOT EXISTS `Favorites` (
        `id` INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
        `user_id` INT NOT NULL,
        `drink_id` INT NOT NULL,
        `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        FOREIGN KEY(user_id) REFERENCES Users(id)
        FOREIGN KEY(drink_id) REFERENCES Drinks(drink_id)
)
;